[arqueocronochile_db]
dialect = "postgresql"
host = "postgresql-arqueocronochile.alwaysdata.net"
port = "5432"
database = "arqueocronochile_db"
username = "arqueocronochile"
password = "FJQ7mtv7hft!aux*zvk"